### ISSUE TITLE
Negative hashes break glsl

### ISSUE THREAD

**Issue by cocreature** [nlguillemot/ShaderSet#1]
First of all let me thank you for this great library!

However when I tried it, I got the weird error

```
Error compiling ../shaders/default.vert:
preamble:2(19): preprocessor error: syntax error, unexpected '-', expecting INTEGER or INTEGER_STRING or NEWLINE
```

Digging through the source I figured out that it was caused by lines such as `#line 1 -716684241`, i.e., `HashName` being negative. This is possible because `HashName` is an `int32_t` but `std::hash` returns a `size_t`.

The same problem can probably occur for `preamble_hash` (but didn’t in my specific example).

**Comment by nlguillemot** [comment]
I'm not sure what's the best way to fix this, since it depends on how the GLSL compiler internally treats the numbers. For example, if `HashName` was `uint32_t`, but the GLSL compiler internally casts it to a `int32_t`, then it wouldn't find the hash inside the error message. Maybe it would work ok to cast it to uint16_t, or alternatively just mask out the 32nd bit.

**Comment by nlguillemot** [comment]
I attempted a fix in 58d1f55 by removing the sign bit. Could you please test to see if it works now?

**Comment by cocreature** [comment]
Works perfectly, thanks for looking into this so quickly.

**Comment by nlguillemot** [comment]
No problem, thanks for reporting the issue and testing it quickly as well. 🙂
