### ISSUE TITLE
Support for multiple shader types in one file

### ISSUE THREAD

**Issue by thomask77** [nlguillemot/ShaderSet#3]
Hi!

It would be nice to have support for complete shader programs in one file by using `#ifdef`:

- https://software.intel.com/en-us/blogs/2012/03/26/using-ifdef-in-opengl-es-20-shaders

I would suggest `.glsl` as the extension, and some type of auto-detection to find out which shaders are contained in the file (like a search for `#ifdef VERTEX_SHADER`, ... during load-time).

best regards,
thomas

**Comment by nlguillemot** [comment]
That's a neat idea, I like it.

One of the design goals of this library was to avoid parsing GLSL, since it's hard to be robust without making a full GLSL preprocessor. I'm not sure how to integrate this feature in a robust way without implementing a preprocessor.

I'm also a bit hesitant because it seems like HLSL compilers are trying to move away from combining shaders in one file. As explained here: http://gamedev.stackexchange.com/questions/68964/is-it-possible-to-compile-both-vs-and-ps-in-a-single-file-in-vs2012

What do you think?

**Comment by nlguillemot** [comment]
I'm thinking that this problem can be generalized: There's currently no way for ShaderSet to let you pass #defines for a shader. If it was possible, having multiple shaders in one file could be implemented on top of it.

How about a pre-shader preamble, that lets you insert your own code at the start of each shader? In that case, you could make an interface that does a string search for `VERTEX_SHADER` & co, then calls ShaderSet::AddProgram with the same file multiple times but different defines.

Just brainstorming.

**Comment by thomask77** [comment]
I already have a prototype running!
Preparing a pull-request right now.
