### ISSUE TITLE
non-blocking timestamp check

### ISSUE THREAD

**Issue by pixelmager** [nlguillemot/ShaderSet#5]
Hey

re https://github.com/nlguillemot/ShaderSet/blob/master/shaderset.cpp#L31

You can use stat on windows as well (like you do on apple), which should not be blocking - something like
```
#include <sys/stat.h>
__time64_t get_file_modify_time( const std::string &in_fullpath )
{
	struct __stat64 stFileInfo;
	int statres = _stat64( in_fullpath.c_str(), &stFileInfo );
	if( statres != 0 ) {
		std::cerr << "## ERR: Problem getting time of \"" << in_fullpath << "\"" << std::endl;
		return 0;
	}
	else {
		return stFileInfo.st_mtime;
	}
}
```
And then of course I still have a todo somewhere to wrap a similar system in folder-notifications, like https://msdn.microsoft.com/en-us/library/windows/desktop/aa365261(v=vs.85).aspx

**Comment by nlguillemot** [comment]
the tricky part is that sometimes another program wants to write to the shader while the file is opened by the ShaderSet.

For example, your text editor might be programmed to request exclusive write ownership of a file when it wants to save it. Therefore, if you press "save" in your text editor at exactly the same time as the ShaderSet tries to read the timestamp, the text editor might fail to open the file handle (because it wants exclusive ownership.)

I don't know if `_stat64` solves that problem, since I assume that `CreateFile` is supposed to be the more low level API on Windows. Does it actually behave differently with regards to ownership of the file?

Monitoring directory changes is brutally complicated, which is why I wanted to omit it from this library. I did implement it "properly" in my PipelineSet class (the D3D12 equivalent of ShaderSet), so it might be possible to lift some code from here: https://github.com/nlguillemot/PipelineSet/blob/master/pipelineset.cpp

It's surprisingly tricky to correctly monitor directory changes. The API and its documentation are just really bad. This blog post (https://qualapps.blogspot.com/2010/05/understanding-readdirectorychangesw.html) and its follow-up were a huge help, so I recommend consulting them if you want to implement something similar.

**Comment by pixelmager** [comment]
Yes, that is the issue that _stat64 solves :)

Thanks for the references on directory-changes, I will soon be reading them religiously! :)

**Comment by nlguillemot** [comment]
fixed, thanks!
